services:
  - type: web
    name: discord-bot
    env: node
    plan: free
    buildCommand: npm install --ignore-scripts
    startCommand: node main.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PREFIX
        sync: false
      - key: MONGOPATH
        sync: false
      - key: OPENAI_KEY
        sync: false